create table seasons (
  sid bigint generated by default as identity primary key,
  name text,
  start_date timestamp,
  end_date timestamp
);

create table players (
  pid bigint generated by default as identity primary key,
  name text,
  price int,
  image text,
  goals int,
  assist int,
  clutch int
);

create table teams (
  tid bigint generated by default as identity primary key,
  sid bigint references public.seasons,
  name text,
  wins int,
  draws int,
  losses int
);

create table users (
  id uuid not null references auth.users on delete cascade,
  is_admin boolean default false,
  cash int default 20000,
  username text,
  PRIMARY key (id)
);

create table fantasy (
  pid bigint generated by default as identity primary key,
  sid bigint references public.seasons,
  players text default '',
  captain int default -1
);