create table seasons (
  sid bigint generated by default as identity primary key,
  name text UNIQUE,
  start_date timestamp,
  end_date timestamp
);

create table players (
  pid bigint generated by default as identity primary key,
  name text,
  price int,
  image text,
  attack int default 50,
  defence int default 50,
  physical int default 50,
  morale int default 50
);

create table playersStats (
  stid bigint generated by default as identity primary key,
  pid bigint references public.players,
  sid bigint references public.seasons,
  goals int default 0,
  assist int default 0,
  wins int default 0,
  clean_sheets int default 0
);

create table teams (
  tid bigint generated by default as identity primary key,
  sid bigint references public.seasons,
  name text UNIQUE,
  color text UNIQUE,
  players int[],
  wins int default 0,
  draws int default 0,
  losses int default 0
);

/* Can add profile name if we make it so that you can check other profiles */
create table users (
  uid uuid not null references auth.users on delete cascade,
  is_admin boolean default false,
  cash int default 20000,
  PRIMARY key (uid)
);

create table usersFantasy (
  fid bigint generated by default as identity primary key,
  uid uuid references public.users,
  sid bigint references public.seasons,
  team_name text,
  players int[] default null,
  captain int default null
);