create table "public"."players" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "player_name" text not null,
    "price" integer not null
);


CREATE UNIQUE INDEX players_pkey ON public.players USING btree (id);

alter table "public"."players" add constraint "players_pkey" PRIMARY KEY using index "players_pkey";


