create table "public"."fantasy_teams" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" character varying,
    "captain_id" integer not null,
    "player_ids" integer[] not null
);


CREATE UNIQUE INDEX "fantasyTeams_pkey" ON public.fantasy_teams USING btree (id);

alter table "public"."fantasy_teams" add constraint "fantasyTeams_pkey" PRIMARY KEY using index "fantasyTeams_pkey";


