create table "public"."bets" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "season_id" bigint not null,
    "bet" character varying not null,
    "value" integer
);


create table "public"."bets_against" (
    "id" bigint generated by default as identity not null,
    "bet_id" bigint not null,
    "user_id" uuid not null
);


CREATE UNIQUE INDEX bets_against_pkey ON public.bets_against USING btree (id);

CREATE UNIQUE INDEX bets_pkey ON public.bets USING btree (id);

alter table "public"."bets" add constraint "bets_pkey" PRIMARY KEY using index "bets_pkey";

alter table "public"."bets_against" add constraint "bets_against_pkey" PRIMARY KEY using index "bets_against_pkey";

alter table "public"."bets" add constraint "bets_season_id_fkey" FOREIGN KEY (season_id) REFERENCES seasons(id) not valid;

alter table "public"."bets" validate constraint "bets_season_id_fkey";

alter table "public"."bets" add constraint "bets_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."bets" validate constraint "bets_user_id_fkey";

alter table "public"."bets_against" add constraint "bets_against_bet_id_fkey" FOREIGN KEY (bet_id) REFERENCES bets(id) not valid;

alter table "public"."bets_against" validate constraint "bets_against_bet_id_fkey";

alter table "public"."bets_against" add constraint "bets_against_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."bets_against" validate constraint "bets_against_user_id_fkey";


