alter table "public"."teams_players" drop constraint "teams_players_pkey";

drop index if exists "public"."teams_players_pkey";

alter table "public"."teams_players" add column "id" bigint generated by default as identity not null;

CREATE UNIQUE INDEX teams_players_pkey ON public.teams_players USING btree (id);

alter table "public"."teams_players" add constraint "teams_players_pkey" PRIMARY KEY using index "teams_players_pkey";


