create table "public"."assists" (
    "id" bigint generated by default as identity not null,
    "player_id" bigint not null,
    "match_id" bigint not null
);


create table "public"."clutches" (
    "id" bigint generated by default as identity not null,
    "player_id" bigint not null,
    "match_id" bigint not null
);


create table "public"."fantasy_teams" (
    "user_id" uuid not null,
    "season_id" bigint not null,
    "name" character varying not null,
    "captain_id" bigint
);


create table "public"."fantasy_teams_players" (
    "season_id" bigint not null,
    "user_id" uuid not null,
    "player_id" bigint not null
);


create table "public"."goals" (
    "id" bigint generated by default as identity not null,
    "match_id" bigint not null,
    "player_id" bigint not null
);


create table "public"."matches" (
    "id" bigint generated by default as identity not null,
    "season_id" bigint not null,
    "team_home_id" bigint not null,
    "team_away_id" bigint not null
);


create table "public"."players" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null default 'Navn Navnesen'::character varying,
    "image" text not null default 'placeholder.png'::text
);


create table "public"."players_seasons" (
    "player_id" bigint not null,
    "season_id" bigint not null,
    "attack" integer not null default 50,
    "defence" integer not null default 50,
    "physical" integer not null default 50,
    "morale" integer not null default 50,
    "price" bigint not null default '3000'::bigint
);


create table "public"."seasons" (
    "id" bigint generated by default as identity not null,
    "start_time" timestamp without time zone not null,
    "deadline_time" timestamp without time zone not null,
    "end_time" timestamp without time zone not null,
    "name" character varying not null,
    "starting_currency" bigint not null default '25000'::bigint
);


create table "public"."teams" (
    "id" bigint generated by default as identity not null,
    "season_id" bigint not null,
    "name" character varying not null,
    "color" character varying not null default 'white'::character varying
);


create table "public"."teams_players" (
    "player_id" bigint not null,
    "team_id" bigint not null
);


alter table "public"."teams_players" enable row level security;

create table "public"."users" (
    "id" uuid not null,
    "is_admin" boolean default false,
    "is_superadmin" boolean default false
);


alter table "public"."users" enable row level security;

CREATE UNIQUE INDEX assists_pkey ON public.assists USING btree (id);

CREATE UNIQUE INDEX clutches_pkey ON public.clutches USING btree (id);

CREATE UNIQUE INDEX fantasy_team_pkey ON public.fantasy_teams USING btree (user_id, season_id);

CREATE UNIQUE INDEX fantasy_teams_players_pkey ON public.fantasy_teams_players USING btree (season_id, user_id, player_id);

CREATE UNIQUE INDEX goals_pkey ON public.goals USING btree (id);

CREATE UNIQUE INDEX matches_pkey ON public.matches USING btree (id);

CREATE UNIQUE INDEX players_pkey ON public.players USING btree (id);

CREATE UNIQUE INDEX players_seasons_pkey ON public.players_seasons USING btree (player_id, season_id);

CREATE UNIQUE INDEX seasons_name_key ON public.seasons USING btree (name);

CREATE UNIQUE INDEX seasons_pkey ON public.seasons USING btree (id);

CREATE UNIQUE INDEX teams_pkey ON public.teams USING btree (id);

CREATE UNIQUE INDEX teams_players_pkey ON public.teams_players USING btree (player_id, team_id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

alter table "public"."assists" add constraint "assists_pkey" PRIMARY KEY using index "assists_pkey";

alter table "public"."clutches" add constraint "clutches_pkey" PRIMARY KEY using index "clutches_pkey";

alter table "public"."fantasy_teams" add constraint "fantasy_team_pkey" PRIMARY KEY using index "fantasy_team_pkey";

alter table "public"."fantasy_teams_players" add constraint "fantasy_teams_players_pkey" PRIMARY KEY using index "fantasy_teams_players_pkey";

alter table "public"."goals" add constraint "goals_pkey" PRIMARY KEY using index "goals_pkey";

alter table "public"."matches" add constraint "matches_pkey" PRIMARY KEY using index "matches_pkey";

alter table "public"."players" add constraint "players_pkey" PRIMARY KEY using index "players_pkey";

alter table "public"."players_seasons" add constraint "players_seasons_pkey" PRIMARY KEY using index "players_seasons_pkey";

alter table "public"."seasons" add constraint "seasons_pkey" PRIMARY KEY using index "seasons_pkey";

alter table "public"."teams" add constraint "teams_pkey" PRIMARY KEY using index "teams_pkey";

alter table "public"."teams_players" add constraint "teams_players_pkey" PRIMARY KEY using index "teams_players_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."assists" add constraint "assists_match_id_fkey" FOREIGN KEY (match_id) REFERENCES matches(id) not valid;

alter table "public"."assists" validate constraint "assists_match_id_fkey";

alter table "public"."assists" add constraint "assists_player_id_fkey" FOREIGN KEY (player_id) REFERENCES players(id) not valid;

alter table "public"."assists" validate constraint "assists_player_id_fkey";

alter table "public"."clutches" add constraint "clutches_match_id_fkey" FOREIGN KEY (match_id) REFERENCES matches(id) not valid;

alter table "public"."clutches" validate constraint "clutches_match_id_fkey";

alter table "public"."clutches" add constraint "clutches_player_id_fkey" FOREIGN KEY (player_id) REFERENCES players(id) not valid;

alter table "public"."clutches" validate constraint "clutches_player_id_fkey";

alter table "public"."fantasy_teams" add constraint "fantasy_teams_captain_id_fkey" FOREIGN KEY (captain_id) REFERENCES players(id) not valid;

alter table "public"."fantasy_teams" validate constraint "fantasy_teams_captain_id_fkey";

alter table "public"."fantasy_teams" add constraint "fantasy_teams_season_id_fkey" FOREIGN KEY (season_id) REFERENCES seasons(id) not valid;

alter table "public"."fantasy_teams" validate constraint "fantasy_teams_season_id_fkey";

alter table "public"."fantasy_teams" add constraint "fantasy_teams_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."fantasy_teams" validate constraint "fantasy_teams_user_id_fkey";

alter table "public"."fantasy_teams_players" add constraint "fantasy_teams_players_player_id_fkey" FOREIGN KEY (player_id) REFERENCES players(id) not valid;

alter table "public"."fantasy_teams_players" validate constraint "fantasy_teams_players_player_id_fkey";

alter table "public"."fantasy_teams_players" add constraint "fantasy_teams_players_season_id_fkey" FOREIGN KEY (season_id) REFERENCES seasons(id) not valid;

alter table "public"."fantasy_teams_players" validate constraint "fantasy_teams_players_season_id_fkey";

alter table "public"."fantasy_teams_players" add constraint "fantasy_teams_players_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."fantasy_teams_players" validate constraint "fantasy_teams_players_user_id_fkey";

alter table "public"."goals" add constraint "goals_match_id_fkey" FOREIGN KEY (match_id) REFERENCES matches(id) not valid;

alter table "public"."goals" validate constraint "goals_match_id_fkey";

alter table "public"."goals" add constraint "goals_player_id_fkey" FOREIGN KEY (player_id) REFERENCES players(id) not valid;

alter table "public"."goals" validate constraint "goals_player_id_fkey";

alter table "public"."matches" add constraint "matches_season_id_fkey" FOREIGN KEY (season_id) REFERENCES seasons(id) not valid;

alter table "public"."matches" validate constraint "matches_season_id_fkey";

alter table "public"."matches" add constraint "matches_team_away_id_fkey" FOREIGN KEY (team_away_id) REFERENCES teams(id) not valid;

alter table "public"."matches" validate constraint "matches_team_away_id_fkey";

alter table "public"."matches" add constraint "matches_team_home_id_fkey" FOREIGN KEY (team_home_id) REFERENCES teams(id) not valid;

alter table "public"."matches" validate constraint "matches_team_home_id_fkey";

alter table "public"."players_seasons" add constraint "players_seasons_player_id_fkey" FOREIGN KEY (player_id) REFERENCES players(id) not valid;

alter table "public"."players_seasons" validate constraint "players_seasons_player_id_fkey";

alter table "public"."players_seasons" add constraint "players_seasons_season_id_fkey" FOREIGN KEY (season_id) REFERENCES seasons(id) not valid;

alter table "public"."players_seasons" validate constraint "players_seasons_season_id_fkey";

alter table "public"."seasons" add constraint "seasons_name_key" UNIQUE using index "seasons_name_key";

alter table "public"."teams" add constraint "teams_season_id_fkey" FOREIGN KEY (season_id) REFERENCES seasons(id) not valid;

alter table "public"."teams" validate constraint "teams_season_id_fkey";

alter table "public"."teams_players" add constraint "teams_players_player_id_fkey" FOREIGN KEY (player_id) REFERENCES players(id) not valid;

alter table "public"."teams_players" validate constraint "teams_players_player_id_fkey";

alter table "public"."teams_players" add constraint "teams_players_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(id) not valid;

alter table "public"."teams_players" validate constraint "teams_players_team_id_fkey";

alter table "public"."users" add constraint "users_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) not valid;

alter table "public"."users" validate constraint "users_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.users (id)
  values (new.id);
  return new;
end;
$function$
;

create policy "Users are viewable by users who created them."
on "public"."users"
as permissive
for select
to public
using ((auth.uid() = id));

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();